### ISSUE TITLE
Announce and update logo

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#25]
![banner](https://user-images.githubusercontent.com/1171852/55528396-469b4f00-56ba-11e9-8b16-3d43d9a27640.png)
```
PyCon India 2019 now has a logo! The logo depicts the skyline and shoreline of Chennai, and the culture within.

#Python #PyConIndia2019
```

**Comment by bravegnu** [comment]
Let's wait for a few +1s before posting the announcement.

**Comment by bravegnu** [comment]
Logo has to be updated in the following locations:

  * Twitter
  * GitHub
  * LinkedIn (if we get access to it)
  * Facebook

Did I miss anything?

**Comment by astronomersiva** [comment]
I'll update the website and blog today evening

**Comment by iamaravindsekar** [comment]
Hello, I would like to get an update on how the website header logo image (PyCon India chennai 2019) should look like, Because the website wireframe has an empty Python logo. Once this gets fixed up It will be easy to proceed with the rest of the designs. For now I have made this image for header. If we already have an alternative fixed in place we can use that. 
![pycon19](https://user-images.githubusercontent.com/20441340/55553744-a9163e80-56fe-11e9-87fa-80d651de4310.png)

**Comment by astronomersiva** [comment]
Hi Aravind,

Our vendor is already working on the website and it should be ready by next week or so. Therefore, let's not overdo the placeholder site.

For now, you can add the logo to the website but out priority now will be to get the poster designs out for CFP and public proposals.

**Comment by iamaravindsekar** [comment]
Alright done... Thank you @astronomersiva

**Comment by gnurenga** [comment]
This announcement is done @bravegnu  shall we close this.
