### ISSUE TITLE
Decide on approaches to make conference special needs friendly

### ISSUE THREAD

**Issue by sharmi** [pythonindia/inpycon2019-tasks#35]

**Comment by zerothabhishek** [comment]
After going through the docs (https://github.com/sharmi/inpycon2019-tasks/blob/master/Diversity/SpecialNeeds.md), here are some relatively easy steps we can take -

- Make the website accessible
- Check if the venues are accessible, esp for wheelchair-bound and visually impaired people
- Add a field in registration form so the person can indicate she has special needs 
- Add a similar field in CFP form
- Train the ground volunteers on the best practices
- Announce and spread the word that we are making the effort, so that people with special needs are motivated to participate and advise.

And a few, slightly difficult steps would be:
- Get a professional review of venues for accessibility
- Actually make the venue infrastructure accessible
- Identify the kinds of disabilities we need to prepare for

**Comment by abhishekmishragithub** [comment]
can keep direction standees as well
