### ISSUE TITLE
Integrate website design from Webchirpy

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#39]
Webchirpy is coming up with the final design for the website. This
needs to be integrated into the website.

**Comment by bravegnu** [comment]
@astronomersiva The final design will be available only on Wednesday.

**Comment by bravegnu** [comment]
Website mockup from Webchirpy is available from https://marvelapp.com/686h7c1/screen/55730870

**Comment by gnurenga** [comment]
Web team did a great job with nice and clean design. The light house in between PyCon India really fits in to the conference.

**Comment by abhishekmishragithub** [comment]
> Website mockup from Webchirpy is available from https://marvelapp.com/686h7c1/screen/55730870

It looks very amazing !!

**Comment by bravegnu** [comment]
Received design update from Webchirpy: http://demo.webchirpy.com/wc72pyc/

**Comment by astronomersiva** [comment]
Sharing some thoughts about the website:

<img height="300" alt="Screen Shot 2019-04-17 at 21 03 38" src="https://user-images.githubusercontent.com/7725225/56333107-77967c00-61b0-11e9-80a1-798e30e4a8ae.png">
^this part can be skipped. Doesn't really add much value but occupies a lot of space

<br>

<img height="300" alt="Screen Shot 2019-04-17 at 21 05 01" src="https://user-images.githubusercontent.com/7725225/56333109-782f1280-61b0-11e9-8693-7a4fe10b8160.png">
Buy Tickets becomes hidden in tablet and mobile view

<br>

<img height="300" alt="Screen Shot 2019-04-17 at 21 06 03" src="https://user-images.githubusercontent.com/7725225/56333111-782f1280-61b0-11e9-98f1-c13db5067658.png">
sponsors and keynote speakers' images should scale down in low resolution devices...they  take up almost an entire scroll worth of size

**Comment by babuenir** [comment]
Also, the font, "Yanone Kaffeesatz" is less legible when compared to other fonts in the page.

![image](https://user-images.githubusercontent.com/3508974/56494732-e1948580-6510-11e9-9425-da93532ac7b9.png)

**Comment by bravegnu** [comment]
![screenshot1](https://user-images.githubusercontent.com/1171852/56752907-02760880-67a7-11e9-89db-0e70918f55e0.png)

1 - the yellow line overshoots the button?
2 - it will be better if this outline is avoided, as suggested by the PSF

![screenshot2](https://user-images.githubusercontent.com/1171852/56752908-02760880-67a7-11e9-89b6-71d276a6c5a2.png)

3 - This is similar to 1
4 - This does not give the indented effect?

![screenshot3](https://user-images.githubusercontent.com/1171852/56752909-030e9f00-67a7-11e9-9064-1639504bc4ba.png)

5 - Can we use a different image here, the Valluvar Kottam is not very clear in this enlarged icon.

![screenshot4](https://user-images.githubusercontent.com/1171852/56752910-030e9f00-67a7-11e9-9cbf-c23265ed3da2.png)

6 - Similar to 1
7 - The lighthouse is not visible here.

**Comment by astronomersiva** [comment]
- The Central Station image in the header section does not scale well on both medium and large screens.
- There is an overlap of the cloud design and the buy tickets button.
![photo6204062044571936918](https://user-images.githubusercontent.com/7725225/56781065-5f051200-67ff-11e9-8ee4-2c4065d35a20.jpg)
- The tickets table is not responsive.
- The yellow border above the buttons should be consistent in size and position everywhere and in all sizes.
- The event schedule table should have more whitespace/some division between different talks.
- We can also do away with the color buttons in the talks table. There are too many colors in that small area and it's distracting.
- The menu toggle in mobile view should be centered vertically.
- Images are too big(speakers, sponsors, venue) in the mobile view. 
- The outline of the snake has to be removed from the speakers section. PSF is not okay with that.
- The cloud animation is abrupt when it reaches the end.
- Like @babuenir said, the font "Yanone Kaffeesatz" is not very legible.
- The lighthouse isn't visible in the footer because of the colors blending together.

**Comment by bravegnu** [comment]
![double-line-header](https://user-images.githubusercontent.com/1171852/56782860-99be7880-6806-11e9-97bb-7b837cb28fea.png)

It will be better if we can avoid the double line-ing of the header.

![triple-line-header](https://user-images.githubusercontent.com/1171852/56782862-9cb96900-6806-11e9-9fa4-14e3dc56a589.png)

And also this triple line-ing of the header.

![text-over-central](https://user-images.githubusercontent.com/1171852/56782869-a3e07700-6806-11e9-8c58-46690d325e3e.png)

The text sometime goes behind the central station image, when the window size is less.

![track-over-content](https://user-images.githubusercontent.com/1171852/56782873-a80c9480-6806-11e9-9b61-4b65d6aa4d1a.png)

We will need to prevent the keynote speaker from getting run-over by the train :-)

**Comment by bravegnu** [comment]
Also notice the train gets offset from the center of the tunnel, when the window width is decreased.

**Comment by webchirpy** [comment]
Hi Team! We are looking into the issues and will update once its done

**Comment by webchirpy** [comment]
Hi Team, we have fixed all the issues. please have your review. We are improvising some minor corrections in the mobile version and will update once done.

**Comment by bravegnu** [comment]
Hi @webchirpy, can you please deliver the files, so that we can integrate them into the website.

**Comment by webchirpy** [comment]
Coding files has been sent through email. Thanks!
