### ISSUE TITLE
Speaker Recommendation Form to discover new speakers

### ISSUE THREAD

**Issue by sharmi** [pythonindia/inpycon2019-tasks#71]
The form is here https://forms.gle/piodZz74SZZuw7M19

The message to be sent with the form (and also present in the form itself)

PyCon India 2019 wants to fairly represent the complete Python community in India. That means not just the Python experts. It also means people from unrelated fields for whom Python just happened to be the best tool for their job.  A tinkerer who made magic with Python. A Pythonista from an underrepresented community. A novice, learning Python from the first time (because learning Python now is not the same as learning Python a decade back). You can recommend any number of speakers.  It is an opportunity to discover the hidden gems of our community. Any Pythonista you believe might have something to share, please recommend. We want to email to them, inviting them to submit a proposal for a talk in PyCon India 2019.
 
Thank you for making PyCon India a better community.

**Comment by sharmi** [comment]
Made a small change to the form again.

https://forms.gle/t84VA4m7fQ5mCnfRA

**Comment by sharmi** [comment]
Shalini caught an important omission. 

If the person who is filling the form is willing to give a talk, there should be a link to call for proposals page.

Added that link. 

The updated form is here https://forms.gle/pUm6VxKXinsE5bpb6

**Comment by sharmi** [comment]
PyCon India 2019 wants to fairly represent the complete Python community in India. 

That means not just the Python experts. It also means people from unrelated fields for whom Python just happened to be the best tool for their job.  A tinkerer who made magic with Python. A Pythonista from an underrepresented community. A novice, learning Python from the first time (because learning Python now is not the same as learning Python a decade back). 

You can recommend any number of speakers.  It is an opportunity to discover the hidden gems of our community. Any Pythonista you believe may have something to share, please recommend. We want to email to them, inviting them to submit a proposal for a talk in PyCon India 2019. 

If you want to propose a talk, the Call For Proposal page is https://in.pycon.org/cfp/2019/proposals/ .

Thank you for making PyCon India a better community.

**Comment by gnurenga** [comment]
@sharmi  Is the above template is  the final one ? Shall we go ahead and post

**Comment by sharmi** [comment]
Yes @gnurenga

**Comment by gnurenga** [comment]
Subject: Regarding Speaker Recommendation for PyCon India 2019

Hi

PyCon India 2019 wants to fairly represent the complete Python
community in India.

That means not just the Python experts. It also means people from
unrelated fields for whom Python just happened to be the best tool for
their job. A tinkerer who made magic with Python. A Pythonista from an
underrepresented community. A novice, learning Python from the first
time (because learning Python now is not the same as learning Python a
decade back).

You can recommend any number of speakers. It is an opportunity to
discover the hidden gems of our community. Any Pythonista you believe
may have something to share, please recommend. We want to email to
them, inviting them to submit a proposal for a talk in PyCon India
2019.

Recommendation form is here  https://forms.gle/piodZz74SZZuw7M19

If you want to propose a talk, the Call For Proposal page is
https://in.pycon.org/cfp/2019/proposals/ .

Thank you for making PyCon India a better community.

Regards
{{Name of the Mailer}}
On Behalf of PyCon India 2019 Organizing Team

**Comment by gnurenga** [comment]
Mail sent to inpycon, chennaipy, hydpy, bangpypers, iot-geeks, chennai-geeknights, pyladies-chennai, ilugc

**Comment by gnurenga** [comment]
@sharmi  I have added the form in to the template mail, also I sent the form to the mailing list as a respond to the previous mail.

**Comment by sharmi** [comment]
ok @gnurenga

**Comment by abhishekmishragithub** [comment]
mail sent to ILUG-BOM, fn+geeks group
