### ISSUE TITLE
Tweet to recommend speakers for PyCon India 2019

### ISSUE THREAD

**Issue by sharmi** [pythonindia/inpycon2019-tasks#76]
Help PyCon India '19 discover the hidden gem of Pythonista speakers in India, from diverse backgrounds and experiences.  https://forms.gle/pUm6VxKXinsE5bpb6

Hint: You can be that gem too.

**Comment by bravegnu** [comment]
I am starting grow little skeptic about this @sharmi We can give it a try if you want. There seems to be no motivation for people to do this.

This is not the case with recommending women speakers, because the women-in-tech are standing up for each because of a shared common cause. They want to change the status-quo.

So it is better to target specific crowds, that feel strongly for each other, rather than the general crowd. Let me know your thoughts on this.

**Comment by bravegnu** [comment]
We can send this out to specific communities like http://www.visionaid.org/about-vision-aid where people stand for each other. And another is http://inclusivestem.org/
