### ISSUE TITLE
Poster presentation copy

### ISSUE THREAD

**Issue by DudeWhoCode** [pythonindia/inpycon2019-tasks#97]
Below is the first draft of poster presentation copy. Suggestions are welcome.

# Welcome to Pycon India Poster Presentation

Posters are the graphical summary of a projects or ideas. They are usually presented in a standard chart paper size, but any creative ways are always welcome.

Pycon India 2019 is will be having a poster presentation session at post lunch, day 1. The poster presentation hall will provide an ample space to present your posters and also to setup a demo on your laptops. We are looking forward to you to present anything interesting, it could be your perspective about a specific python project, new idea or whats going on in the python community. This will give you an opportunity to start the one on one conversations with the attendees and who knows, you might end up having a brainstorming session with a huge crowd :)

# Tips on a preparing a good poster
- Keep the topic niche
- While textual representation is good, graphical representation will attract more eyes
- Make sure the contents are properly sized and spaced in the poster so that its viweable from decent distance
- Provoke the reader's curiosity which will open up space for futher discussions

**Topics for posters include, but not limited to:**
1. Embedded Python and IOT - MicroPython, Python on Hardware, Robotics, Arduino and Raspberry Pi
2. Networking and Security - Network Programming, Network Security and Encryption
3. Web development - Web, Apis, Microservices
4. Developer tools and automation - Testing, CI/CD, Containers, Orchestration, Logging and Monitoring
5. Data Science, Machine Learning and AI
6. Core Python - Language Features, Python Implementations, Extending Python and Standard Library, language internals
7. Desktop Applications - Qt, GTK+, Tkinter, Gnome, KDE, Accessibility
8. Scientific Computing - Python usage in scientific computing and research. GIS, Mathematics, Simulations
9. Game Design and 3D Modelling - Python in developing games, 3-D modelling and animation
10. Culture and society - Diversity, health, productivity, workspace issues, privacy, community building, coding for causes
11. Others - Everything else that may be of interest to the audience.

# Questions and Discussions
Contact the coordinators through email:
Naren - narenravi92@gmail.com 
Abhishek - zerothabhishek@gmail.com
The team: cfp@in.pycon.org

**Comment by bravegnu** [comment]
# Posters for PyCon India 2019

Posters are graphical summary of projects or ideas. They are usually presented with an A0 size poster, but any creative ways are always welcome. The poster session provides an opportunity to network with the conference attendees and acts as a starting point for further discussions. While talks generally needs to appeal to a wide section of the community, posters can cover niche topics. 

PyCon India 2019 will be having a poster presentation session at post lunch, day 1. During the poster presentation session you will be provided with a poster board that can hold an A0 size poster, and a table to place your laptop, for demos. Conference attendees interested in your topic, will stop by, during which you can give them a brief presentation / demo.

## Timeline

  * Poster CFP opens: 3rd June, 2019
  * Poster CFP closes: 1st August, 2019
  * Selected posters announced: 15th August, 2019
  * Draft posters to be submitted On: 15th September, 2019
  * Posters will be presented on: 12th October, 2019

## FAQ

### What is the difference between a talk and a poster?

Talks and posters are different ways of interacting with the conference audience. A topic can be presented as talk, if the intention is to explain the topic in detail. A poster on the other hand, is similar to a lightning talk, in that it quickly introduces the audience to a topic, and acts as trigger point for further discussion.

There some specific cases where posters are better suited than talks:

   * Due to the nature of the poster presentation format, it is better suite for demos, the attendees can interact with the project. This is especially useful for hardware projects.

   * If you are first time conference attendee, or a first time speaker at a conference, posters let you engage with the audience without getting intimated by the large crowd.

   * Niche topics that are domain heavy, are better suited as posters. Examples: Python in local language computing, Python in embedded Linux build automation, Python used in scientific study of ailments, etc.

### Can I submit both a talk and poster proposal?

You can submit a talk and poster proposal for the same topic. If your talk does not get selected, you can use the poster session, to introduce your topic, and engage with the audience. Given the limited space and time at the conference, only one of them will get selected though.

### What makes a good poster?

First, ensure that you select a good title. Conference attendees will use it to determine, which posters to attend. Make sure it brings in audience who will be interested in your poster.  

Second, the poster itself. Here are a few tips for creating the poster:
- While textual representation is good, graphical representation will attract more eyes
- Make sure the contents are properly sized and spaced in the poster so that it is viewable from decent distance
- Provoke the reader's curiosity which will open up space for further discussions
- Provide links for the attendees to know more about the topic and connect with you / the community

### Do you have sample poster proposals to get started?

You can check the poster proposals from other conferences:

  * PySangamam 2018: https://pysangamam.org/blog/2018/08/29/announcing-selected-posters/
  * PyCon US 2019: https://us.pycon.org/2019/schedule/posters/list/

### Can I do a poster in a local language?

Yes! Since attendees can choose which poster they want to attend, your poster can be in a local language. This makes sense only if there will be sufficient no. of participants who are familiar with the language. This can also be done, if the topic is itself about projects / libraries on regional language computing. Please be noted that the proposal itself needs to be in English, for the reviewers to be able to comprehend your proposal.

## Questions and Discussions
Contact the coordinators through email:
Naren - narenravi92@gmail.com 
Abhishek - zerothabhishek@gmail.com
The team: cfp@in.pycon.org

**Comment by abhishekmishragithub** [comment]
@DudeWhoCode @bravegnu  this is still in draft ?

**Comment by bravegnu** [comment]
@abhishekmishragithub We should be getting this up on the CFP site shortly.

**Comment by DudeWhoCode** [comment]
@abhishekmishragithub For now Vijay's update is finalized. But you can still give suggestions.

**Comment by abhishekmishragithub** [comment]
@DudeWhoCode keeping some examples/reference will be more helpful.
